
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "${PORT:-3001}:${PORT:-3001}" #Use PORT from .env, default to 3001
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    environment:
          DATABASE_URL: ${DATABASE_URL}
          PORT: ${PORT:-3001}


  #PostgreSQL Database (local development only)
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: postgres_container
  #   restart: always
  #   ports:
  #     - "${DB_PORT:-5432}:5432"
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  #Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend


#(local development only)
# volumes:
#   postgres_data: